PROCESS_DATA_SCRIPT = 'process_data.m';
FILTER_DATA_SCRIPT = 'filter_data.m';
NEURO_MUSCULAR_MODEL_SCRIPT = 'NMM_script2.m';

run(PROCESS_DATA_SCRIPT);
run(FILTER_DATA_SCRIPT);
run(NEURO_MUSCULAR_MODEL_SCRIPT);